// app/api/Nationalities/route.ts
import { NextResponse } from "next/server";

// GET handler para obtener la lista de nacionalidades
export async function GET() {
  const nationalities = [
    { sigla: "AF", nombre: "Afganistán", nombreIngles: "AFGHANISTAN" },
    { sigla: "ZA", nombre: "Sudáfrica", nombreIngles: "SOUTH AFRICA" },
    { sigla: "AL", nombre: "Albania", nombreIngles: "ALBANIA" },
    { sigla: "DE", nombre: "Alemania", nombreIngles: "GERMANY" },
    { sigla: "AD", nombre: "Andorra", nombreIngles: "ANDORRA" },
    { sigla: "AO", nombre: "Angola", nombreIngles: "ANGOLA" },
    { sigla: "AI", nombre: "Anguila", nombreIngles: "ANGUILLA" },
    { sigla: "AG", nombre: "Antigua y Barbuda", nombreIngles: "ANTIGUA AND BARBUDA" },
    { sigla: "AN", nombre: "Antillas Holandesas", nombreIngles: "NETHERLANDS ANTILLES" },
    { sigla: "SA", nombre: "Arabia Saudita", nombreIngles: "SAUDI ARABIA" },
    { sigla: "DZ", nombre: "Argelia", nombreIngles: "ALGERIA" },
    { sigla: "AR", nombre: "Argentina", nombreIngles: "ARGENTINA" },
    { sigla: "AM", nombre: "Armenia", nombreIngles: "ARMENIA" },
    { sigla: "AW", nombre: "Aruba", nombreIngles: "ARUBA" },
    { sigla: "AU", nombre: "Australia", nombreIngles: "AUSTRALIA" },
    { sigla: "AT", nombre: "Austria", nombreIngles: "AUSTRIA" },
    { sigla: "AZ", nombre: "Azerbaiyán", nombreIngles: "AZERBAIJAN" },
    { sigla: "BS", nombre: "Bahamas", nombreIngles: "BAHAMAS" },
    { sigla: "BD", nombre: "Bangladesh", nombreIngles: "BANGLADESH" },
    { sigla: "BB", nombre: "Barbados", nombreIngles: "BARBADOS" },
    { sigla: "BH", nombre: "Baréin", nombreIngles: "BAHREIN" },
    { sigla: "BE", nombre: "Bélgica", nombreIngles: "BELGIUM" },
    { sigla: "BZ", nombre: "Belice", nombreIngles: "BELIZE" },
    { sigla: "BJ", nombre: "Benín", nombreIngles: "BENIN" },
    { sigla: "BM", nombre: "Islas Bermudas", nombreIngles: "BERMUDA" },
    { sigla: "BY", nombre: "Bielorrusia", nombreIngles: "BELARUS" },
    { sigla: "BO", nombre: "Bolivia", nombreIngles: "BOLIVIA" },
    { sigla: "BA", nombre: "Bosnia Herzegovina", nombreIngles: "BOSNIA HERZEGOVINA" },
    { sigla: "BW", nombre: "Botsuana", nombreIngles: "BOTSWANA" },
    { sigla: "BR", nombre: "Brasil", nombreIngles: "BRAZIL" },
    { sigla: "BN", nombre: "Brunéi", nombreIngles: "BRUNEI DARUSSALAM" },
    { sigla: "BG", nombre: "Bulgaria", nombreIngles: "BULGARIA" },
    { sigla: "BF", nombre: "Burkina Faso", nombreIngles: "BURKINA FASO" },
    { sigla: "BI", nombre: "Burundi", nombreIngles: "BURUNDI" },
    { sigla: "BT", nombre: "Bután", nombreIngles: "BHUTAN" },
    { sigla: "CV", nombre: "Cabo Verde", nombreIngles: "CAPE VERDE ISLANDS" },
    { sigla: "CM", nombre: "Camerún", nombreIngles: "CAMEROON" },
    { sigla: "KH", nombre: "Camboya", nombreIngles: "CAMBODIA" },
    { sigla: "CA", nombre: "Canadá", nombreIngles: "CANADA" },
    { sigla: "QA", nombre: "Katar", nombreIngles: "QATAR" },
    { sigla: "KZ", nombre: "Kazajstán", nombreIngles: "KAZAKHSTAN" },
    { sigla: "TD", nombre: "Chad", nombreIngles: "CHAD" },
    { sigla: "CL", nombre: "Chile", nombreIngles: "CHILE" },
    { sigla: "CN", nombre: "China", nombreIngles: "CHINA" },
    { sigla: "CY", nombre: "Chipre", nombreIngles: "CYPRUS" },
    { sigla: "CO", nombre: "Colombia", nombreIngles: "COLOMBIA" },
    { sigla: "CG", nombre: "Congo", nombreIngles: "CONGO" },
    { sigla: "KP", nombre: "Corea del Norte", nombreIngles: "KOREA – DEM. PEOPLE’S RE" },
    { sigla: "KR", nombre: "Corea del Sur", nombreIngles: "KOREA – REP. OF" },
    { sigla: "CI", nombre: "Costa de Marfil", nombreIngles: "COTE D’IVOIRE" },
    { sigla: "CR", nombre: "Costa Rica", nombreIngles: "COSTA RICA" },
    { sigla: "HR", nombre: "Croacia", nombreIngles: "CROATIA" },
    { sigla: "CU", nombre: "Cuba", nombreIngles: "CUBA" },
    { sigla: "CW", nombre: "Curazao", nombreIngles: "CURACAO" },
    { sigla: "DK", nombre: "Dinamarca", nombreIngles: "DENMARK" },
    { sigla: "DJ", nombre: "Yibuti", nombreIngles: "DJIBOUTI" },
    { sigla: "DM", nombre: "Dominica", nombreIngles: "DOMINICA" },
    { sigla: "EG", nombre: "Egipto", nombreIngles: "EGYPT" },
    { sigla: "SV", nombre: "El Salvador", nombreIngles: "EL SALVADOR" },
    { sigla: "AE", nombre: "Emiratos Árabes Unidos", nombreIngles: "UNITED ARAB EMIRATES" },
    { sigla: "EC", nombre: "Ecuador", nombreIngles: "ECUADOR" },
    { sigla: "ER", nombre: "Eritrea", nombreIngles: "ERITREA" },
    { sigla: "SK", nombre: "Eslovaquia", nombreIngles: "SLOVAK REPUBLIC" },
    { sigla: "SI", nombre: "Eslovenia", nombreIngles: "SLOVENIA" },
    { sigla: "ES", nombre: "España", nombreIngles: "SPAIN" },
    { sigla: "US", nombre: "Estados Unidos", nombreIngles: "UNITED STATES" },
    { sigla: "EE", nombre: "Estonia", nombreIngles: "ESTONIA" },
    { sigla: "ET", nombre: "Etiopía", nombreIngles: "ETHIOPIA" },
    { sigla: "FJ", nombre: "Fiyi", nombreIngles: "FIJI ISLANDS" },
    { sigla: "PH", nombre: "Filipinas", nombreIngles: "PHILIPPINES" },
    { sigla: "FI", nombre: "Finlandia", nombreIngles: "FINLAND" },
    { sigla: "FR", nombre: "Francia", nombreIngles: "FRANCE" },
    { sigla: "GA", nombre: "Gabón", nombreIngles: "GABON" },
    { sigla: "GM", nombre: "Gambia", nombreIngles: "THE GAMBIA" },
    { sigla: "GH", nombre: "Gana", nombreIngles: "GHANA" },
    { sigla: "GI", nombre: "Gibraltar", nombreIngles: "GIBRALTAR" },
    { sigla: "GD", nombre: "Granada", nombreIngles: "GRENADA" },
    { sigla: "GR", nombre: "Grecia", nombreIngles: "GREECE" },
    { sigla: "GL", nombre: "Groenlandia", nombreIngles: "GREENLAND" },
    { sigla: "GP", nombre: "Guadalupe", nombreIngles: "GUADELOUPE" },
    { sigla: "GU", nombre: "Guam", nombreIngles: "GUAM" },
    { sigla: "GT", nombre: "Guatemala", nombreIngles: "GUATEMALA" },
    { sigla: "GY", nombre: "Guayana", nombreIngles: "GUYANA" },
    { sigla: "GF", nombre: "Guayana Francesa", nombreIngles: "FRENCH GUIANA" },
    { sigla: "GN", nombre: "Guinea", nombreIngles: "GUINEA" },
    { sigla: "GQ", nombre: "Guinea Ecuatorial", nombreIngles: "EQUATORIAL GUINEA" },
    { sigla: "GW", nombre: "Guinea-Bisáu", nombreIngles: "GUINEA BISSAU" },
    { sigla: "HT", nombre: "Haití", nombreIngles: "HAITI" },
    { sigla: "NL", nombre: "Países Bajos", nombreIngles: "NETHERLANDS" },
    { sigla: "HN", nombre: "Honduras", nombreIngles: "HONDURAS" },
    { sigla: "HK", nombre: "Hong Kong", nombreIngles: "HONG KONG" },
    { sigla: "HU", nombre: "Hungría", nombreIngles: "HUNGARY" },
    { sigla: "YE", nombre: "Yemen", nombreIngles: "YEMEN ARAB REP." },
    { sigla: "BV", nombre: "Isla Bouvet", nombreIngles: "BOUVET ISLAND" },
    { sigla: "UM", nombre: "Isla Periférica Menor", nombreIngles: "U.S. MINOR OUTLYING ISLA" },
    { sigla: "NF", nombre: "Isla Norfolk", nombreIngles: "NORFOLK ISLAND" },
    { sigla: "RE", nombre: "Isla Reunión", nombreIngles: "REUNION ISLAND" },
    { sigla: "ST", nombre: "Isla Santo Tomé y Príncipe", nombreIngles: "SÃO TOMÉ AND PRÍNCIPE" },
    { sigla: "KY", nombre: "Islas Caimán", nombreIngles: "CAYMAN ISLANDS" },
    { sigla: "CX", nombre: "Islas de Navidad", nombreIngles: "CHRISTMAS ISLAND" },
    { sigla: "CC", nombre: "Islas de Coco", nombreIngles: "COCOS ISLANDS" },
    { sigla: "KM", nombre: "Islas Comoras", nombreIngles: "COMORO ISLANDS" },
    { sigla: "CK", nombre: "Islas Cook", nombreIngles: "COOK ISLANDS" },
    { sigla: "FK", nombre: "Islas Malvinas", nombreIngles: "FALKLAND ISLANDS" },
    { sigla: "FO", nombre: "Islas Faroe", nombreIngles: "FAROE ISLANDS" },
    { sigla: "HM", nombre: "Islas Heard & McDonald", nombreIngles: "HEARD AND MCDONALD ISLAN" },
    { sigla: "MP", nombre: "Islas Marianas del Norte", nombreIngles: "NORTHERN MARIANA ISLANDS" },
    { sigla: "MH", nombre: "Islas Marshall", nombreIngles: "MARSHALL ISLANDS" },
    { sigla: "MU", nombre: "Islas Mauricio", nombreIngles: "MAURITIUS" },
    { sigla: "SB", nombre: "Islas Salomón", nombreIngles: "SOLOMON ISLANDS" },
    { sigla: "SJ", nombre: "Islas Svalbard y Jan Mayan", nombreIngles: "SVALBARD & JAN MAYAN ISL" },
    { sigla: "TC", nombre: "Islas Turcas y Caicos", nombreIngles: "TURKS AND CAICOS ISLANDS" },
    { sigla: "VI", nombre: "Islas Vírgenes de los Estados Unidos", nombreIngles: "U.S.VIRGIN ISLANDS" },
    { sigla: "VG", nombre: "Islas Vírgenes Británicas", nombreIngles: "BRITISH VIRGIN ISLANDS" },
    { sigla: "WF", nombre: "Islas Wallis y Futuna", nombreIngles: "WALLIS AND FUTUNA ISLAND" },
    { sigla: "IN", nombre: "India", nombreIngles: "INDIA" },
    { sigla: "ID", nombre: "Indonesia", nombreIngles: "INDONESIA" },
    { sigla: "IG", nombre: "Inglaterra", nombreIngles: "ENGLAND" },
    { sigla: "IR", nombre: "Irán", nombreIngles: "IRAN" },
    { sigla: "IQ", nombre: "Irak", nombreIngles: "IRAQ" },
    { sigla: "IE", nombre: "Irlanda", nombreIngles: "IRELAND" },
    { sigla: "IS", nombre: "Islandia", nombreIngles: "ICELAND" },
    { sigla: "IL", nombre: "Israel", nombreIngles: "ISRAEL" },
    { sigla: "IT", nombre: "Italia", nombreIngles: "ITALY" },
    { sigla: "YU", nombre: "Yugoslavia", nombreIngles: "YUGOSLAVIA" },
    { sigla: "JM", nombre: "Jamaica", nombreIngles: "JAMAICA" },
    { sigla: "JP", nombre: "Japón", nombreIngles: "JAPAN" },
    { sigla: "JO", nombre: "Jordán", nombreIngles: "JORDAN" },
    { sigla: "KI", nombre: "Kiribati", nombreIngles: "KIRIBATI" },
    { sigla: "KW", nombre: "Kuwait", nombreIngles: "KUWAIT" },
    { sigla: "LA", nombre: "Laos", nombreIngles: "LAOS" },
    { sigla: "LS", nombre: "Lesoto", nombreIngles: "LESOTHO" },
    { sigla: "LV", nombre: "Letonia", nombreIngles: "LATVIA" },
    { sigla: "LB", nombre: "Líbano", nombreIngles: "LEBANON" },
    { sigla: "LR", nombre: "Liberia", nombreIngles: "LIBERIA" },
    { sigla: "LY", nombre: "Libia", nombreIngles: "LIBYA ARAB JAMAHIRIYA" },
    { sigla: "LI", nombre: "Liechtenstein", nombreIngles: "LIECHTENSTEIN" },
    { sigla: "LT", nombre: "Lituania", nombreIngles: "LITHUANIA" },
    { sigla: "LU", nombre: "Luxemburgo", nombreIngles: "LUXEMBOURG" },
    { sigla: "MK", nombre: "Macedonia", nombreIngles: "MACEDONIA" },
    { sigla: "MG", nombre: "Madagascar", nombreIngles: "MALAGASY REPUBLIC" },
    { sigla: "MY", nombre: "Malasia", nombreIngles: "MALAYSIA" },
    { sigla: "MW", nombre: "Malauí", nombreIngles: "MALAWI" },
    { sigla: "MV", nombre: "Maldivas", nombreIngles: "MALDIVES" },
    { sigla: "ML", nombre: "Malí", nombreIngles: "MALI" },
    { sigla: "MT", nombre: "Malta", nombreIngles: "MALTA" },
    { sigla: "MA", nombre: "Marruecos", nombreIngles: "MOROCCO" },
    { sigla: "MQ", nombre: "Martinica", nombreIngles: "MARTINIQUE" },
    { sigla: "IM", nombre: "Mauricio", nombreIngles: "MAURICIA" },
    { sigla: "MR", nombre: "Mauritania", nombreIngles: "MAURITANIA" },
    { sigla: "YT", nombre: "Mayotte", nombreIngles: "MAYOTTE" },
    { sigla: "MX", nombre: "México", nombreIngles: "MEXICO" },
    { sigla: "MM", nombre: "Birmania", nombreIngles: "MYANMAR" },
    { sigla: "FM", nombre: "Micronesia", nombreIngles: "MICRONESIA" },
    { sigla: "MZ", nombre: "Mozambique", nombreIngles: "MOZAMBIQUE" },
    { sigla: "MD", nombre: "Moldavia", nombreIngles: "MOLDOVA" },
    { sigla: "MC", nombre: "Mónaco", nombreIngles: "MONACO" },
    { sigla: "MN", nombre: "Mongolia", nombreIngles: "MONGOLIA" },
    { sigla: "ME", nombre: "Montenegro", nombreIngles: "MONTENEGRO" },
    { sigla: "MS", nombre: "Montserrat", nombreIngles: "MONTSERRAT" },
    { sigla: "NA", nombre: "Namibia", nombreIngles: "NAMIBIA" },
    { sigla: "NR", nombre: "Nauru", nombreIngles: "NAURU" },
    { sigla: "NP", nombre: "Nepal", nombreIngles: "NEPAL" },
    { sigla: "NI", nombre: "Nicaragua", nombreIngles: "NICARAGUA" },
    { sigla: "NE", nombre: "Níger", nombreIngles: "NIGER" },
    { sigla: "NG", nombre: "Nigeria", nombreIngles: "NIGERIA" },
    { sigla: "NU", nombre: "Niue", nombreIngles: "NIUE" },
    { sigla: "NO", nombre: "Noruega", nombreIngles: "NORWAY" },
    { sigla: "NC", nombre: "Nueva Caledonia", nombreIngles: "NEW CALEDONIA" },
    { sigla: "NZ", nombre: "Nueva Zelanda", nombreIngles: "NEW ZEALAND" },
    { sigla: "OM", nombre: "Omán", nombreIngles: "OMAN" },
    { sigla: "PW", nombre: "Palaos", nombreIngles: "PALAU" },
    { sigla: "PS", nombre: "Palestina", nombreIngles: "PALESTINA" },
    { sigla: "PA", nombre: "Panamá", nombreIngles: "PANAMA CITY" },
    { sigla: "PG", nombre: "Papúa Nueva Guinea", nombreIngles: "PAPUA NEW GUINEA" },
    { sigla: "PK", nombre: "Pakistán", nombreIngles: "PAKISTAN" },
    { sigla: "PY", nombre: "Paraguay", nombreIngles: "PARAGUAY" },
    { sigla: "PE", nombre: "Perú", nombreIngles: "PERU" },
    { sigla: "PN", nombre: "Pitcairn", nombreIngles: "PITCAIRN" },
    { sigla: "PF", nombre: "Polinesia Francesa", nombreIngles: "FRENCH POLYNESIA" },
    { sigla: "PL", nombre: "Polonia", nombreIngles: "POLAND" },
    { sigla: "PR", nombre: "Puerto Rico", nombreIngles: "PUERTO RICO" },
    { sigla: "PT", nombre: "Portugal", nombreIngles: "PORTUGAL" },
    { sigla: "KE", nombre: "Kenia", nombreIngles: "KENYA" },
    { sigla: "KG", nombre: "Kirguistán", nombreIngles: "KYRGYZSTAN" },
    { sigla: "GB", nombre: "Reino Unido", nombreIngles: "UNITED KINGDOM" },
    { sigla: "CF", nombre: "República Centroafricana", nombreIngles: "CENTRAL AFRICAN REPUBLIC" },
    { sigla: "GE", nombre: "Republica de Georgia", nombreIngles: "GEORGIA" },
    { sigla: "CD", nombre: "República Democrática del Congo", nombreIngles: "CONGO DEMOCRATIC REP." },
    { sigla: "DO", nombre: "República Dominicana", nombreIngles: "DOMINICAN REPUBLIC" },
    { sigla: "CZ", nombre: "República Checa", nombreIngles: "CZECH REPUBLIC" },
    { sigla: "RO", nombre: "Rumania", nombreIngles: "ROMANIA" },
    { sigla: "RW", nombre: "Ruanda", nombreIngles: "RWANDA" },
    { sigla: "RU", nombre: "Rusia", nombreIngles: "RUSSIAN FEDERATION" },
    { sigla: "EH", nombre: "Sahara Occidental", nombreIngles: "WESTERN SAHARA" },
    { sigla: "BL", nombre: "San Bartolomé", nombreIngles: "SAINT BARTHELEMY" },
    { sigla: "PM", nombre: "San Pedro y Miquelón", nombreIngles: "SAINT PIERRE AND MIQUELON" },
    { sigla: "AS", nombre: "Samoa Americana", nombreIngles: "AMERICAN SAMOA" },
    { sigla: "WS", nombre: "Samoa Occidental", nombreIngles: "WESTERN SAMOA" },
    { sigla: "SM", nombre: "San Marino", nombreIngles: "SAN MARINO" },
    { sigla: "SH", nombre: "Santa Helena", nombreIngles: "SAINT HELENA" },
    { sigla: "LC", nombre: "Santa Lucía", nombreIngles: "SAINT LUCIA" },
    { sigla: "KN", nombre: "San Cristóbal y Nieves", nombreIngles: "SAINT KITTS AND NEVIS" },
    { sigla: "TS", nombre: "San Martín", nombreIngles: "SAINT MARTIN" },
    { sigla: "VC", nombre: "San Vicente y las Granadinas", nombreIngles: "SAINT VINCENT AND THE GRENADINES" },
    { sigla: "YC", nombre: "Seychelles", nombreIngles: "SEYCHELLES" },
    { sigla: "SN", nombre: "Senegal", nombreIngles: "SENEGAL" },
    { sigla: "SL", nombre: "Sierra Leona", nombreIngles: "SIERRA LEONE" },
    { sigla: "RS", nombre: "Serbia", nombreIngles: "SERBIA" },
    { sigla: "SG", nombre: "Singapur", nombreIngles: "SINGAPORE" },
    { sigla: "SY", nombre: "Siria", nombreIngles: "SYRIA" },
    { sigla: "SO", nombre: "Somalia", nombreIngles: "SOMALIA" },
    { sigla: "LK", nombre: "Sri Lanka", nombreIngles: "SRI LANKA" },
    { sigla: "SZ", nombre: "Suazilandia", nombreIngles: "SWAZILAND" },
    { sigla: "SD", nombre: "Sudán", nombreIngles: "SUDAN" },
    { sigla: "SS", nombre: "Sudán del Sur", nombreIngles: "SOUTH SUDAN" },
    { sigla: "SE", nombre: "Suecia", nombreIngles: "SWEDEN" },
    { sigla: "CH", nombre: "Suiza", nombreIngles: "SWITZERLAND" },
    { sigla: "SR", nombre: "Surinam", nombreIngles: "SURINAME" },
    { sigla: "TJ", nombre: "Tayikistán", nombreIngles: "TAJKISTAN" },
    { sigla: "TH", nombre: "Tailandia", nombreIngles: "THAILAND" },
    { sigla: "TW", nombre: "Taiwán", nombreIngles: "TAIWAN" },
    { sigla: "TZ", nombre: "Tanzania", nombreIngles: "TANZANIA" },
    { sigla: "TL", nombre: "Timor Oriental", nombreIngles: "TIMOR-LESTE" },
    { sigla: "TG", nombre: "Togo", nombreIngles: "TOGO" },
    { sigla: "TK", nombre: "Tokelau", nombreIngles: "TOKELAU" },
    { sigla: "TO", nombre: "Tonga", nombreIngles: "TONGA" },
    { sigla: "TT", nombre: "Trinidad y Tobago", nombreIngles: "TRINIDAD AND TOBAGO" },
    { sigla: "TN", nombre: "Túnez", nombreIngles: "TUNISIA" },
    { sigla: "TM", nombre: "Turkmenistán", nombreIngles: "TURKMENISTAN" },
    { sigla: "TC", nombre: "Turcas y Caicos", nombreIngles: "TURKS AND CAICOS ISLANDS" },
    { sigla: "TR", nombre: "Turquía", nombreIngles: "TURKEY" },
    { sigla: "TV", nombre: "Tuvalu", nombreIngles: "TUVALU" },
    { sigla: "UA", nombre: "Ucrania", nombreIngles: "UKRAINE" },
    { sigla: "UG", nombre: "Uganda", nombreIngles: "UGANDA" },
    { sigla: "UY", nombre: "Uruguay", nombreIngles: "URUGUAY" },
    { sigla: "UZ", nombre: "Uzbekistán", nombreIngles: "UZBEKISTAN" },
    { sigla: "VU", nombre: "Vanuatu", nombreIngles: "VANUATU" },
    { sigla: "VE", nombre: "Venezuela", nombreIngles: "VENEZUELA" },
    { sigla: "VN", nombre: "Vietnam", nombreIngles: "VIETNAM" },
    { sigla: "ZM", nombre: "Zambia", nombreIngles: "ZAMBIA" },
    { sigla: "ZW", nombre: "Zimbabue", nombreIngles: "ZIMBABWE" }
  ];

  return NextResponse.json({ nationalities });
}
